# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeRoulette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Моя рулетка', max_length=100, verbose_name='Название рулетки')),
                ('spin_duration', models.IntegerField(default=5, help_text='Сколько секунд крутится колесо', verbose_name='Длительность вращения (секунды)')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('anime', 'Аниме-тема')], default='dark', max_length=20, verbose_name='Тема')),
                ('wheel_size', models.CharField(choices=[('small', 'Малый (300px)'), ('medium', 'Средний (400px)'), ('large', 'Большой (500px)')], default='medium', max_length=20, verbose_name='Размер колеса')),
                ('display_mode', models.CharField(choices=[('posters', 'Постеры'), ('titles', 'Названия'), ('both', 'Постеры и названия')], default='both', max_length=20, verbose_name='Режим отображения')),
                ('color_scheme', models.CharField(choices=[('rainbow', 'Радуга'), ('rating', 'По рейтингу'), ('monochrome', 'Монохром')], default='rainbow', max_length=20, verbose_name='Цветовая схема')),
                ('animation_style', models.CharField(choices=[('smooth', 'Плавная'), ('fast', 'Быстрая'), ('cinematic', 'Кинематографичная')], default='smooth', max_length=20, verbose_name='Стиль анимации')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Звук включён')),
                ('sound_type', models.CharField(default='default', help_text='default, tick, whoosh, custom', max_length=50, verbose_name='Тип звука')),
                ('default_spin_count', models.IntegerField(default=1, help_text='Сколько аниме выбирать за раз', verbose_name='Количество аниме по умолчанию')),
                ('weight_mode', models.CharField(choices=[('proportional', 'Пропорционально'), ('rating', 'Только рейтинг'), ('manual', 'Ручные')], default='proportional', max_length=20, verbose_name='Режим расчёта весов')),
                ('exclude_recent', models.BooleanField(default=False, help_text='Исключать аниме, которые недавно выпадали', verbose_name='Исключать недавно выпавшие')),
                ('exclusion_period', models.IntegerField(default=7, help_text='Сколько дней не показывать выпавшее аниме', verbose_name='Период исключения (дней)')),
                ('max_items', models.IntegerField(default=50, help_text='Максимальное количество аниме в колесе', verbose_name='Максимум аниме в колесе')),
                ('max_spin_items', models.IntegerField(default=10, help_text='Максимальное количество аниме, которые можно выбрать за раз', verbose_name='Максимум аниме за раз')),
                ('history_limit', models.IntegerField(default=100, help_text='Сколько записей истории хранить', verbose_name='Лимит истории')),
                ('auto_add_from_collection', models.BooleanField(default=False, verbose_name='Автоматически добавлять из коллекции')),
                ('auto_add_from_playlists', models.BooleanField(default=False, verbose_name='Автоматически добавлять из плейлистов')),
                ('last_spin_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рулетка аниме',
                'verbose_name_plural': 'Рулетки аниме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimeRouletteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anime_id', models.IntegerField(verbose_name='ID аниме')),
                ('anime_title', models.CharField(max_length=255, verbose_name='Название аниме')),
                ('anime_poster', models.URLField(blank=True, null=True, verbose_name='Постер аниме')),
                ('weight', models.IntegerField(default=1, help_text='Чем больше вес, тем больше сектор на колесе', verbose_name='Вес')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='Цвет сектора')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Элемент рулетки',
                'verbose_name_plural': 'Элементы рулетки',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoulettePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название набора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('items_data', models.JSONField(default=list, help_text='Список элементов в формате [{"anime_id": 1, "weight": 2, "color": "#fff"}, ...]', verbose_name='Данные элементов')),
                ('settings_snapshot', models.JSONField(default=dict, help_text='Настройки рулетки на момент создания пресета', verbose_name='Снимок настроек')),
                ('items_count', models.IntegerField(default=0, verbose_name='Количество аниме')),
                ('times_used', models.IntegerField(default=0, verbose_name='Количество использований')),
                ('is_public', models.BooleanField(default=False, help_text='Другие пользователи могут использовать этот набор', verbose_name='Публичный набор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пресет рулетки',
                'verbose_name_plural': 'Пресеты рулетки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouletteStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_spins', models.IntegerField(default=0, verbose_name='Всего круток')),
                ('single_spins', models.IntegerField(default=0, verbose_name='Одиночных круток')),
                ('multiple_spins', models.IntegerField(default=0, verbose_name='Множественных круток')),
                ('marathon_spins', models.IntegerField(default=0, verbose_name='Марафонов')),
                ('most_spun_anime_id', models.IntegerField(blank=True, null=True, verbose_name='ID самого частого аниме')),
                ('most_spun_count', models.IntegerField(default=0, verbose_name='Количество выпадений')),
                ('least_spun_anime_id', models.IntegerField(blank=True, null=True, verbose_name='ID самого редкого аниме')),
                ('least_spun_count', models.IntegerField(default=0, verbose_name='Количество выпадений')),
                ('unique_anime_spun', models.IntegerField(default=0, verbose_name='Уникальных аниме выпало')),
                ('last_7_days_spins', models.IntegerField(default=0, verbose_name='Круток за 7 дней')),
                ('last_30_days_spins', models.IntegerField(default=0, verbose_name='Круток за 30 дней')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roulette', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='roulette.animeroulette')),
            ],
            options={
                'verbose_name': 'Статистика рулетки',
                'verbose_name_plural': 'Статистика рулеток',
            },
        ),
        migrations.CreateModel(
            name='RouletteSpinHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spin_type', models.CharField(choices=[('single', 'Одиночная'), ('multiple', 'Множественная'), ('marathon', 'Марафон')], default='single', max_length=20, verbose_name='Тип крутки')),
                ('rotation_angle', models.FloatField(verbose_name='Угол поворота')),
                ('spin_duration', models.FloatField(verbose_name='Длительность вращения')),
                ('items_count', models.IntegerField(default=1, verbose_name='Количество выбранных аниме')),
                ('is_favorite', models.BooleanField(default=False, help_text='Пользователь добавил результат в избранное', verbose_name='В избранном')),
                ('notes', models.TextField(blank=True, help_text='Заметки пользователя к результату', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_history', to='roulette.animeroulette')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='roulette.animerouletteitem')),
                ('winners', models.ManyToManyField(blank=True, help_text='Для множественного выбора и марафона', related_name='multi_wins', to='roulette.animerouletteitem')),
            ],
            options={
                'verbose_name': 'История крутки',
                'verbose_name_plural': 'История круток',
                'ordering': ['-created_at'],
            },
        ),
    ]
