# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roulette', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettepreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animerouletteitem',
            name='roulette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='roulette.animeroulette'),
        ),
        migrations.AddField(
            model_name='animeroulette',
            name='last_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_in', to='roulette.animerouletteitem'),
        ),
        migrations.AddField(
            model_name='animeroulette',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulettes', to=settings.AUTH_USER_MODEL),
        ),
    ]
