# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('complaint_type', models.CharField(choices=[('playlist', 'Плейлист'), ('playlist_item', 'Элемент плейлиста'), ('comment', 'Комментарий'), ('reactor_post', 'Reactor пост'), ('group', 'Группа'), ('dub', 'Озвучка'), ('user', 'Пользователь')], max_length=20)),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('harassment', 'Харассмент'), ('inappropriate', 'Неподходящий контент'), ('copyright', 'Нарушение авторских прав'), ('misleading', 'Вводящая в заблуждение информация'), ('broken_link', 'Битая ссылка'), ('duplicate', 'Дубликат'), ('other', 'Другое')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('investigating', 'Расследуется'), ('resolved', 'Решена'), ('dismissed', 'Отклонена')], default='pending', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк'), ('heart', 'Сердечко'), ('comment', 'Комментарий'), ('reply', 'Ответ на комментарий'), ('mention', 'Упоминание'), ('follow', 'Подписка'), ('repost', 'Репост'), ('message', 'Сообщение'), ('group_message', 'Сообщение в группе'), ('group_invite', 'Приглашение в группу'), ('achievement', 'Достижение'), ('contest', 'Новый конкурс'), ('contest_vote', 'Голосование'), ('contest_results', 'Результаты конкурса'), ('contest_win', 'Победа в конкурсе'), ('reminder_episode', 'Напоминание о серии'), ('reminder_event', 'Напоминание о событии'), ('reminder_contest', 'Напоминание о конкурсе'), ('system', 'Системное'), ('warning', 'Предупреждение'), ('security', 'Безопасность')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_settings', models.JSONField(default=dict)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('dnd_enabled', models.BooleanField(default=False)),
                ('dnd_start', models.TimeField(blank=True, null=True)),
                ('dnd_end', models.TimeField(blank=True, null=True)),
                ('auto_clean_read_days', models.IntegerField(default=30)),
                ('auto_clean_unread_days', models.IntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField(verbose_name='Время напоминания')),
                ('repeat_weekly', models.BooleanField(default=False, verbose_name='Повторять еженедельно')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('enable_sound', models.BooleanField(default=True, verbose_name='Звук уведомления')),
                ('enable_push', models.BooleanField(default=True, verbose_name='Пуш-уведомление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_triggered', models.BooleanField(default=False, verbose_name='Сработало')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['-reminder_time'],
            },
        ),
    ]
