# Generated by Django 4.2.10 on 2026-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment', 'Комментарий'), ('like', 'Лайк'), ('follow', 'Подписка'), ('mention', 'Упоминание'), ('group_invite', 'Приглашение в группу'), ('contest', 'Конкурс'), ('message', 'Сообщение'), ('system', 'Системное')], max_length=20),
        ),
    ]
