version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: anisphere_mysql
    restart: always
    environment:
      MYSQL_DATABASE: u3384518_anisphere_db
      MYSQL_USER: u3384518
      MYSQL_PASSWORD: dv7uuc8BY8w5Hqx
      MYSQL_ROOT_PASSWORD: rootpassword123
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - anisphere_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword123"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  backend:
    build: .
    container_name: anisphere_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_NAME=u3384518_anisphere_db
      - DB_USER=u3384518
      - DB_PASSWORD=dv7uuc8BY8w5Hqx
      - DB_HOST=mysql
      - DB_PORT=3306
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=django-insecure-v9de-w3%n@%4qm%w=$$dn^pg18_k9gi_f-^o_(q^!edyixqpe9e
      - REDIS_HOST=redis
    volumes:
      - ./data/staticfiles:/app/staticfiles
      - ./data/media:/app/media
      - .:/app  # Монтируем весь проект для разработки
    networks:
      - anisphere_network

  redis:
    image: redis:7
    container_name: anisphere_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - anisphere_network

networks:
  anisphere_network:
    driver: bridge
