# Generated by Django 4.2.10 on 2026-01-29 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
