# Generated by Django 4.2.10 on 2026-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_playlistitem_options_playlist_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['position', 'added_at'], 'verbose_name': 'Элемент плейлиста', 'verbose_name_plural': 'Элементы плейлиста'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='source_url',
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
    ]
