# Generated by Django 4.2.10 on 2026-02-11 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0006_alter_playlist_options_alter_playlistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteanime',
            options={'verbose_name': 'Избранное аниме', 'verbose_name_plural': 'Избранные аниме'},
        ),
        migrations.AlterModelOptions(
            name='favoriteplaylist',
            options={'verbose_name': 'Избранный плейлист', 'verbose_name_plural': 'Избранные плейлисты'},
        ),
        migrations.AlterField(
            model_name='favoriteanime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favoriteanime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_anime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteplaylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
