# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videosource',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sources', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='video_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='anime.videosource'),
        ),
        migrations.AddField(
            model_name='userepisodeprogress',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_progress', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='userepisodeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdubrating',
            name='dub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='anime.dub'),
        ),
        migrations.AddField(
            model_name='userdubrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivetab',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_viewers', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='useractivetab',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_tabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translation',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_translations', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='translation',
            name='video_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='anime.videosource'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_playlists', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='anime.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_episodes', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.videosource'),
        ),
        migrations.AddField(
            model_name='dubrole',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='anime.voiceactor'),
        ),
        migrations.AddField(
            model_name='dubrole',
            name='dub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='anime.dub'),
        ),
        migrations.AddField(
            model_name='dub',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_dubs', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='dub',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_dubs', to='anime.dubstudio'),
        ),
        migrations.AddField(
            model_name='customdub',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dubs', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='customdub',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_dubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customdub',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_dubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliptask',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_tasks', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='cliptask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clip_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animeupdate',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='animeoped',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oped', to='anime.anime', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='animeepisodenotification',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_notifications', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='animeepisodenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anime',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='anime.franchise', verbose_name='Франшиза'),
        ),
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together={('user', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='videosource',
            unique_together={('anime', 'source', 'quality')},
        ),
        migrations.AlterUniqueTogether(
            name='videoquality',
            unique_together={('video_source', 'quality')},
        ),
        migrations.AlterUniqueTogether(
            name='userepisodeprogress',
            unique_together={('user', 'anime', 'episode_number')},
        ),
        migrations.AlterUniqueTogether(
            name='userdubrating',
            unique_together={('user', 'dub')},
        ),
        migrations.AlterUniqueTogether(
            name='useractivetab',
            unique_together={('user', 'anime')},
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('anime', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'anime')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='dub',
            unique_together={('anime', 'studio')},
        ),
        migrations.AlterUniqueTogether(
            name='customdub',
            unique_together={('anime', 'created_by', 'name')},
        ),
        migrations.AddIndex(
            model_name='cliptask',
            index=models.Index(fields=['status', 'created_at'], name='anime_clipt_status_ff7294_idx'),
        ),
        migrations.AddIndex(
            model_name='cliptask',
            index=models.Index(fields=['user', 'status'], name='anime_clipt_user_id_8c373d_idx'),
        ),
        migrations.AddIndex(
            model_name='cliptask',
            index=models.Index(fields=['task_type', 'status'], name='anime_clipt_task_ty_824333_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='animeoped',
            unique_together={('anime', 'episode_number')},
        ),
        migrations.AlterUniqueTogether(
            name='animeepisodenotification',
            unique_together={('user', 'anime')},
        ),
    ]
