# Generated by Django 4.2.10 on 2026-01-17 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('quality', models.CharField(choices=[('bd', 'Blu-ray'), ('dvd', 'DVD'), ('tv', 'TV'), ('web', 'Web'), ('unknown', 'Неизвестно')], default='unknown', max_length=20)),
                ('player_url', models.URLField(blank=True)),
                ('download_url', models.URLField(blank=True)),
                ('torrent_url', models.URLField(blank=True)),
                ('episodes_count', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('votes_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_dubs', to='anime.anime')),
            ],
            options={
                'ordering': ['-rating', '-released_at'],
            },
        ),
        migrations.CreateModel(
            name='DubStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('vk_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('is_official', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('closed', 'Закрыта')], default='active', max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('works_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Студия озвучки',
                'verbose_name_plural': 'Студии озвучки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_original', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('photo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('vk_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DubRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200)),
                ('character_name_original', models.CharField(blank=True, max_length=200)),
                ('role_type', models.CharField(choices=[('main', 'Главная роль'), ('supporting', 'Второстепенная роль'), ('guest', 'Эпизодическая роль'), ('narrator', 'Рассказчик')], default='supporting', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='anime.voiceactor')),
                ('dub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='anime.dub')),
            ],
            options={
                'ordering': ['order', 'character_name'],
            },
        ),
        migrations.AddField(
            model_name='dub',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_dubs', to='anime.dubstudio'),
        ),
        migrations.CreateModel(
            name='UserDubRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='anime.dub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dub')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dub',
            unique_together={('anime', 'studio')},
        ),
    ]
