# Generated by Django 4.2.10 on 2026-02-21 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0002_add_kodik_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, verbose_name='Скриншоты'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_translations', to='anime.anime'),
        ),
        migrations.CreateModel(
            name='CustomDub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название озвучки')),
                ('studio', models.CharField(blank=True, max_length=255, verbose_name='Студия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='720p', max_length=10, verbose_name='Качество')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL логотипа')),
                ('episodes_done', models.PositiveIntegerField(default=0, verbose_name='Озвучено серий')),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего серий')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершено')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('ratings_count', models.PositiveIntegerField(default=0, verbose_name='Оценок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dubs', to='anime.anime')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_dubs', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_dubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользовательская озвучка',
                'verbose_name_plural': 'Пользовательские озвучки',
                'ordering': ['-created_at'],
                'unique_together': {('anime', 'created_by', 'name')},
            },
        ),
    ]
