# Generated by Django 4.2.10 on 2026-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002b_dub_dubstudio_voiceactor_dubrole_dub_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='search_text',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['search_text'], name='anime_anime_search__3eba09_idx'),
        ),
    ]
