# Generated by Django 4.2.10 on 2026-02-04 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0005_anime_screenshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Элемент плейлиста',
                'verbose_name_plural': 'Элементы плейлиста',
                'ordering': ['position', 'added_at'],
            },
        ),
        # Сначала удаляем поле screenshots
        migrations.RemoveField(
            model_name='anime',
            name='screenshots',
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-score', 'title_ru'], 'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name'], 'verbose_name': 'Студия', 'verbose_name_plural': 'Студии'},
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_anime_title_r_1450af_idx',
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_anime_title_e_2e763f_idx',
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_anime_search__3eba09_idx',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='aired_from',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='aired_to',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='anilist_id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='anime_type',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='description_source',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='poster_file',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='scored_by',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='trailer_url',
        ),
        migrations.AlterField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='data_source',
            field=models.CharField(choices=[('shikimori', 'Shikimori'), ('mal', 'MyAnimeList'), ('demo', 'Демо')], default='shikimori', max_length=20, verbose_name='Источник данных'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество эпизодов'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, to='anime.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID MyAnimeList'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster_url',
            field=models.URLField(blank=True, verbose_name='URL постера'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='search_text',
            field=models.TextField(blank=True, verbose_name='Поисковый текст'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='shikimori_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID Shikimori'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Онгоинг'), ('finished', 'Завершено'), ('announced', 'Анонсировано')], default='finished', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, to='anime.studio', verbose_name='Студии'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (английское)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_jp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (японское)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название (русское)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['data_source'], name='anime_anime_data_so_e40ad3_idx'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_playlists', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='anime.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'anime')},
        ),
        # Добавляем поле screenshots как JSONField
        migrations.AddField(
            model_name='anime',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, verbose_name='Скриншоты'),
        ),
    ]
