# Generated by Django 4.2.10 on 2026-02-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_playlist_playlistitem_alter_anime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, verbose_name='URL трейлера'),
        ),
    ]
