# Generated by Django 4.2.10 on 2026-02-06 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0007_anime_trailer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('kodik', 'Kodik'), ('aniboom', 'AniBoom'), ('jutsu', 'Jutsu'), ('shikimori', 'Shikimori')], max_length=20, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Внешний ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quality', models.CharField(choices=[('360', '360p'), ('480', '480p'), ('720', '720p'), ('1080', '1080p'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Качество')),
                ('video_format', models.CharField(default='mp4', max_length=20, verbose_name='Формат видео')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (секунды)')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байты)')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('m3u8_url', models.URLField(blank=True, verbose_name='M3U8 плейлист')),
                ('mpd_content', models.TextField(blank=True, verbose_name='MPD контент')),
                ('download_url', models.URLField(blank=True, verbose_name='Ссылка для скачивания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sources', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Источник видео',
                'verbose_name_plural': 'Источники видео',
                'ordering': ['-created_at'],
                'unique_together': {('anime', 'source', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название перевода')),
                ('translation_type', models.CharField(choices=[('voice', 'Озвучка'), ('subtitles', 'Субтитры'), ('dubbing', 'Дубляж')], default='voice', max_length=20, verbose_name='Тип перевода')),
                ('studio_name', models.CharField(blank=True, max_length=255, verbose_name='Студия')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Внешний ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('processing', 'В обработке'), ('error', 'Ошибка')], default='active', max_length=20, verbose_name='Статус')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершен')),
                ('episodes_count', models.PositiveIntegerField(default=0, verbose_name='Количество эпизодов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='anime.anime')),
                ('video_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='anime.videosource')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['-created_at'],
                'unique_together': {('anime', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер эпизода')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Название (англ.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_episodes', to='anime.anime')),
                ('video_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.videosource')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['number'],
                'unique_together': {('anime', 'number')},
            },
        ),
        migrations.CreateModel(
            name='AnimeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('new_episode', 'Новый эпизод'), ('new_translation', 'Новый перевод'), ('quality_update', 'Обновление качества'), ('status_change', 'Изменение статуса'), ('info_update', 'Обновление информации')], max_length=20, verbose_name='Тип обновления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер эпизода')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Уведомлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Обновление аниме',
                'verbose_name_plural': 'Обновления аниме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.PositiveIntegerField(default=0, verbose_name='Текущее время (секунды)')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (секунды)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('watch_count', models.PositiveIntegerField(default=1, verbose_name='Количество просмотров')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='anime.anime')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='anime.episode')),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='anime.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс просмотра',
                'verbose_name_plural': 'Прогрессы просмотра',
                'ordering': ['-last_watched'],
                'unique_together': {('user', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=10, verbose_name='Качество')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='Разрешение')),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Битрейт')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('m3u8_url', models.URLField(blank=True, verbose_name='M3U8 плейлист')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('video_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='anime.videosource')),
            ],
            options={
                'verbose_name': 'Качество видео',
                'verbose_name_plural': 'Качества видео',
                'ordering': ['-quality'],
                'unique_together': {('video_source', 'quality')},
            },
        ),
    ]
