# Generated by Django 4.2.10 on 2026-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_videosource_translation_episode_animeupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='shikimori_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Shikimori'),
        ),
    ]
