# Generated by Django 4.2.10 on 2026-02-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_anime_shikimori_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-created_at'], 'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_anime_year_38d697_idx',
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_anime_status_6458e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_anime_score_fc3b7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_anime_data_so_e40ad3_idx',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='mal_id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='screenshots',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studios',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='anime_posters/', verbose_name='Постер аниме'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='data_source',
            field=models.CharField(default='unknown', max_length=20, verbose_name='Источник данных'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='shikimori_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Онгоинг'), ('finished', 'Завершен'), ('announced', 'Анонсирован'), ('canceled', 'Отменен')], default='finished', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_jp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на японском'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
