# Generated by Django 4.2.10 on 2026-02-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_anime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='kind',
            field=models.CharField(choices=[('tv', 'ТВ сериал'), ('movie', 'Фильм'), ('ova', 'OVA'), ('special', 'Спецвыпуск'), ('ona', 'ONA'), ('music', 'Клип'), ('franchise', 'Франшиза')], default='tv', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='anime',
            name='movie_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество фильмов'),
        ),
        migrations.AddField(
            model_name='anime',
            name='movies',
            field=models.JSONField(blank=True, default=list, verbose_name='Фильмы франшизы'),
        ),
        migrations.AddField(
            model_name='anime',
            name='ova_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество OVA'),
        ),
        migrations.AddField(
            model_name='anime',
            name='ovas',
            field=models.JSONField(blank=True, default=list, verbose_name='OVA франшизы'),
        ),
        migrations.AddField(
            model_name='anime',
            name='total_items',
            field=models.PositiveIntegerField(default=1, verbose_name='Общее количество элементов'),
        ),
    ]
