# Generated by Django 4.2.10 on 2026-02-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_anime_kind_anime_movie_count_anime_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.JSONField(blank=True, default=list, verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.JSONField(blank=True, default=list, verbose_name='Студии'),
        ),
    ]
