# Generated by Django 4.2.10 on 2026-01-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='dub_studio',
        ),
    ]
