# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dub_type', models.CharField(choices=[('full', 'Полная озвучка'), ('subtitles', 'Субтитры'), ('partial', 'Частичная озвучка'), ('voiceover', 'Закадровый перевод')], default='full', max_length=20)),
                ('quality', models.CharField(choices=[('unknown', 'Неизвестно'), ('low', 'Низкое'), ('medium', 'Среднее'), ('high', 'Высокое'), ('excellent', 'Отличное')], default='unknown', max_length=20)),
                ('episodes_done', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_abandoned', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True)),
                ('torrent_url', models.URLField(blank=True)),
                ('player_url', models.URLField(blank=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('last_episode_at', models.DateField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Озвучка',
                'verbose_name_plural': 'Озвучки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('name_jp', models.CharField(blank=True, max_length=200, verbose_name='Название (японское)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL логотипа')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dub_groups/logos/', verbose_name='Логотип')),
                ('banner_url', models.URLField(blank=True, verbose_name='URL баннера')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='dub_groups/banners/', verbose_name='Баннер')),
                ('website', models.URLField(blank=True, verbose_name='Официальный сайт')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('discord_url', models.URLField(blank=True, verbose_name='Discord')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('works_count', models.IntegerField(default=0, verbose_name='Всего озвучек')),
                ('tv_count', models.PositiveIntegerField(default=0, verbose_name='ТВ сериалов')),
                ('movie_count', models.PositiveIntegerField(default=0, verbose_name='Фильмов')),
                ('ova_count', models.PositiveIntegerField(default=0, verbose_name='OVA/ONA')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Средний рейтинг')),
                ('subscribers_count', models.PositiveIntegerField(default=0, verbose_name='Подписчиков')),
                ('genre_stats', models.JSONField(blank=True, default=dict, verbose_name='Статистика жанров')),
                ('translation_type', models.CharField(choices=[('voice', 'Озвучка'), ('subtitles', 'Субтитры'), ('both', 'Оба')], default='voice', max_length=20, verbose_name='Тип перевода')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('closed', 'Закрыта')], default='active', max_length=20, verbose_name='Статус')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирована')),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа озвучки',
                'verbose_name_plural': 'Группы озвучки',
                'ordering': ['-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DubGroupDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок темы')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislikes_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Обсуждение группы озвучки',
                'verbose_name_plural': 'Обсуждения групп озвучки',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DubGroupDiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ответ на обсуждение',
                'verbose_name_plural': 'Ответы на обсуждения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DubGroupNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость группы озвучки',
                'verbose_name_plural': 'Новости групп озвучки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DubGroupRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_quality', models.IntegerField(default=5, verbose_name='Качество озвучки')),
                ('timing', models.IntegerField(default=5, verbose_name='Синхронизация')),
                ('translation', models.IntegerField(default=5, verbose_name='Перевод')),
                ('consistency', models.IntegerField(default=5, verbose_name='Постоянство')),
                ('overall_rating', models.FloatField(verbose_name='Общая оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оценка группы озвучки',
                'verbose_name_plural': 'Оценки групп озвучки',
            },
        ),
        migrations.CreateModel(
            name='DubGroupSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписка на группу озвучки',
                'verbose_name_plural': 'Подписки на группы озвучки',
            },
        ),
        migrations.CreateModel(
            name='DubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('jutsu', 'Jut.su'), ('animego', 'AnimeGo'), ('animedia', 'Animedia'), ('anime365', 'Anime365'), ('other', 'Другое')], max_length=50)),
                ('url', models.URLField()),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['episode'],
            },
        ),
        migrations.CreateModel(
            name='DubReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('text', models.TextField()),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DubRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200)),
                ('character_name_en', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_main', 'character_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('name_jp', models.CharField(blank=True, max_length=200, verbose_name='Имя (японское)')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL фото')),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('roles', models.JSONField(default=list, verbose_name='Роли')),
                ('works_count', models.IntegerField(default=0, verbose_name='Количество работ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='voice_actors/')),
                ('roles_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='voice_actors', to='dubs.dubgroup')),
            ],
            options={
                'verbose_name': 'Актёр озвучки',
                'verbose_name_plural': 'Актёры озвучки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDubPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='dubs.dubgroup')),
            ],
        ),
    ]
