# Generated by Django 4.2.10 on 2026-01-17 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0002b_dub_dubstudio_voiceactor_dubrole_dub_studio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dub_type', models.CharField(choices=[('full', 'Полная озвучка'), ('subtitles', 'Субтитры'), ('partial', 'Частичная озвучка'), ('voiceover', 'Закадровый перевод')], default='full', max_length=20)),
                ('quality', models.CharField(choices=[('unknown', 'Неизвестно'), ('low', 'Низкое'), ('medium', 'Среднее'), ('high', 'Высокое'), ('excellent', 'Отличное')], default='unknown', max_length=20)),
                ('episodes_done', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_abandoned', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True)),
                ('torrent_url', models.URLField(blank=True)),
                ('player_url', models.URLField(blank=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('last_episode_at', models.DateField(blank=True, null=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dubs_works', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Озвучка',
                'verbose_name_plural': 'Озвучки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('vk_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='dub_groups/logos/')),
                ('works_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('closed', 'Закрыта')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа озвучки',
                'verbose_name_plural': 'Группы озвучки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='voice_actors/')),
                ('roles_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='voice_actors', to='dubs.dubgroup')),
            ],
            options={
                'verbose_name': 'Актёр озвучки',
                'verbose_name_plural': 'Актёры озвучки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('jutsu', 'Jut.su'), ('animego', 'AnimeGo'), ('animedia', 'Animedia'), ('anime365', 'Anime365'), ('other', 'Другое')], max_length=50)),
                ('url', models.URLField()),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('dub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dubs.dub')),
            ],
            options={
                'ordering': ['episode'],
            },
        ),
        migrations.AddField(
            model_name='dub',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_dubs', to='dubs.dubgroup'),
        ),
        migrations.CreateModel(
            name='UserDubPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='dubs.dubgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='DubRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200)),
                ('character_name_en', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dubs.voiceactor')),
                ('dub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dubs.dub')),
            ],
            options={
                'ordering': ['-is_main', 'character_name'],
                'unique_together': {('dub', 'actor', 'character_name')},
            },
        ),
        migrations.CreateModel(
            name='DubReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('text', models.TextField()),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dubs.dub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dub', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dub',
            unique_together={('anime', 'group')},
        ),
    ]
