# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dubs', '0001_initial'),
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdubpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='related_anime',
            field=models.ManyToManyField(blank=True, related_name='related_people', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='dubrole',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dubs.voiceactor'),
        ),
        migrations.AddField(
            model_name='dubrole',
            name='dub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dubs.dub'),
        ),
        migrations.AddField(
            model_name='dubreview',
            name='dub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dubs.dub'),
        ),
        migrations.AddField(
            model_name='dubreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dublink',
            name='dub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dubs.dub'),
        ),
        migrations.AddField(
            model_name='dubgroupsubscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='dubs.dubgroup'),
        ),
        migrations.AddField(
            model_name='dubgroupsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_group_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dubgrouprating',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dubs.dubgroup'),
        ),
        migrations.AddField(
            model_name='dubgrouprating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_group_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dubgroupnews',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dub_group_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dubgroupnews',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='dubs.dubgroup'),
        ),
        migrations.AddField(
            model_name='dubgroupdiscussionreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_group_discussion_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dubgroupdiscussionreply',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dubs.dubgroupdiscussion'),
        ),
        migrations.AddField(
            model_name='dubgroupdiscussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dub_group_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dubgroupdiscussion',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='dubs.dubgroup'),
        ),
        migrations.AddField(
            model_name='dub',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dubs_works', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='dub',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dub',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_dubs', to='dubs.dubgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='userdubpreference',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['slug'], name='dubs_person_slug_d23fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='dubs_person_name_55243d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dubrole',
            unique_together={('dub', 'actor', 'character_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dubreview',
            unique_together={('dub', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='dubgroupsubscription',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='dubgrouprating',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='dub',
            unique_together={('anime', 'group')},
        ),
    ]
