# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('playlists', '0002_initial'),
        ('reactor', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostnotinterested',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userposthidden',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for_users', to='social.post'),
        ),
        migrations.AddField(
            model_name='userposthidden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotinterested',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotinterested',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermention',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='social.post'),
        ),
        migrations.AddField(
            model_name='usermention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_in_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userglobalchatstyle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_chat_style', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='social.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.supportticket'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repost',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='social.post'),
        ),
        migrations.AddField(
            model_name='repost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='social.message'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatusersettings',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='privatechatusersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatsettings',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='privatechatsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_settings_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='social.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posthashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_links', to='social.hashtag'),
        ),
        migrations.AddField(
            model_name='posthashtag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_links', to='social.post'),
        ),
        migrations.AddField(
            model_name='postdislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='social.post'),
        ),
        migrations.AddField(
            model_name='postdislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.postcomment'),
        ),
        migrations.AddField(
            model_name='postcommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentdislike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='social.postcomment'),
        ),
        migrations.AddField(
            model_name='postcommentdislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.postcomment'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='social.post'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='social.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.group'),
        ),
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts_of', to='social.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='post',
            name='reactor_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='reactor.reactorpost'),
        ),
        migrations.AddField(
            model_name='post',
            name='spoiler_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoiler_posts', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='social.message'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='social.message'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_emoji_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages_v2', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_info', to='social.message'),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='pinned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagepin',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages_v2', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_attachments', to='social.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to', to='social.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='social.post'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_shorts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='reactor.reactorpost'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='social.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembersettings',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_settings', to='social.chatmember'),
        ),
        migrations.AddField(
            model_name='groupchatsettings',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_settings', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='social.post'),
        ),
        migrations.AddField(
            model_name='feedview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestvote',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.contest'),
        ),
        migrations.AddField(
            model_name='contestvote',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.contestentry'),
        ),
        migrations.AddField(
            model_name='contestvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='social.contest'),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='anime.anime'),
        ),
        migrations.AddField(
            model_name='contest',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_to', to='social.comment'),
        ),
        migrations.AddField(
            model_name='chatwallpaper',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallpapers', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatwallpaper',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallpapers', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='chatwallpaper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_wallpapers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chattypingstatus',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='chattypingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_topics', to='anime.anime', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='social.groupchat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_themes', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_themes', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chattagassignment',
            name='group_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chattagassignment',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='social.privatechat'),
        ),
        migrations.AddField(
            model_name='chattagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='social.chattag'),
        ),
        migrations.AddField(
            model_name='chattag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatslowmode',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slow_mode_settings', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrole',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatrole',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrestriction',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatrestriction',
            name='restricted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_restrictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrestriction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_restrictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.chatrole'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatjoinrequest',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatinvitelink',
            name='auto_assign_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_links', to='social.chatrole', verbose_name='Автоматически назначаемая роль'),
        ),
        migrations.AddField(
            model_name='chatinvitelink',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatinvitelink',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invite_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatinvitelink',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_invite_links', to=settings.AUTH_USER_MODEL, verbose_name='Целевой пользователь'),
        ),
        migrations.AddField(
            model_name='chatinvite',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatinvite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatfolderchat',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='social.chatfolder'),
        ),
        migrations.AddField(
            model_name='chatfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatban',
            name='banned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatban',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatbackup',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatbackup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatadminlog',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='social.groupchat'),
        ),
        migrations.AddField(
            model_name='chatadminlog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.message'),
        ),
        migrations.AddField(
            model_name='chatadminlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatadminlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='social.post'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='social.message'),
        ),
        migrations.AddField(
            model_name='antispamrule',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_spam_rules', to='social.groupchat'),
        ),
        migrations.AddIndex(
            model_name='userpostnotinterested',
            index=models.Index(fields=['user', 'created_at'], name='social_user_user_id_685823_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpostnotinterested',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='userposthidden',
            index=models.Index(fields=['user', 'created_at'], name='social_user_user_id_95198c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userposthidden',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='usernotinterested',
            index=models.Index(fields=['user', 'created_at'], name='social_user_user_id_d73c4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotinterested',
            unique_together={('user', 'target_user')},
        ),
        migrations.AddIndex(
            model_name='usermention',
            index=models.Index(fields=['user', 'is_notified'], name='social_user_user_id_fd2e8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermention',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'uploaded_at'], name='social_uplo_user_id_1a28c0_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='social_supp_user_id_62c621_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='social_supp_status_9db65a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='social_supp_ticket__08f68b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender', 'created_at'], name='social_supp_sender__8e1086_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user', 'created_at'], name='social_secu_user_id_fc749c_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['is_suspicious'], name='social_secu_is_susp_ee2f87_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['scheduled_at', 'status'], name='social_sche_schedul_ea7c49_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['user', 'created_at'], name='social_repo_user_id_dfd2de_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['original_post', 'created_at'], name='social_repo_origina_08b763_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repost',
            unique_together={('user', 'original_post')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', 'created_at'], name='social_repo_reporte_67a78c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'content_id'], name='social_repo_content_a1eb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='social_repo_status_6921a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['message', 'created_at'], name='social_reac_message_ddcc39_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', 'created_at'], name='social_reac_user_id_6f1fdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AlterUniqueTogether(
            name='privatechatusersettings',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='privatechatsettings',
            index=models.Index(fields=['user', 'is_pinned'], name='social_priv_user_id_a04a48_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechatsettings',
            index=models.Index(fields=['user', 'is_archived'], name='social_priv_user_id_efca43_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechatsettings',
            index=models.Index(fields=['user', 'is_hidden'], name='social_priv_user_id_c9e0f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechatsettings',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user1', 'last_message_at'], name='social_priv_user1_i_572f69_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user2', 'last_message_at'], name='social_priv_user2_i_d61c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user1', 'user1_pinned'], name='social_priv_user1_i_d69881_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user2', 'user2_pinned'], name='social_priv_user2_i_9fcb4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'order'], name='social_post_post_id_03f225_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'created_at'], name='social_post_post_id_657d47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='posthashtag',
            index=models.Index(fields=['hashtag', 'post'], name='social_post_hashtag_aace02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posthashtag',
            unique_together={('post', 'hashtag')},
        ),
        migrations.AddIndex(
            model_name='postdislike',
            index=models.Index(fields=['post', 'created_at'], name='social_post_post_id_7d991c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postdislike',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postcommentlike',
            index=models.Index(fields=['comment', 'created_at'], name='social_post_comment_37c648_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postcommentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='postcommentdislike',
            index=models.Index(fields=['comment', 'created_at'], name='social_post_comment_53c99c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postcommentdislike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', 'created_at'], name='social_post_post_id_daac6b_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', 'path'], name='social_post_post_id_e7fc65_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['author', 'created_at'], name='social_post_author__392544_idx'),
        ),
        migrations.AddIndex(
            model_name='postattachment',
            index=models.Index(fields=['post', 'content_type'], name='social_post_post_id_7bb823_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postattachment',
            unique_together={('post', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='social_post_author__76003c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', 'created_at'], name='social_post_group_i_d0d7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['anime', 'created_at'], name='social_post_anime_i_76a223_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', 'created_at'], name='social_post_is_pinn_2aadf9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'created_at'], name='social_post_status_cf0f35_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', 'created_at'], name='social_post_visibil_2fa219_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'created_at'], name='social_post_post_ty_7ccba2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='social_mess_message_c9d10c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'content_type'], name='social_mess_message_d66f47_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='social_mess_content_8ef88c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='social_mess_chat_id_10cc41_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='social_mess_sender__12caae_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'topic_id', 'created_at'], name='social_mess_chat_id_57fcd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['created_at'], name='social_grou_created_ebb347_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['is_public'], name='social_grou_is_publ_127c76_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['anime'], name='social_grou_anime_i_a6e278_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'created_at'], name='social_foll_followe_7ff834_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', 'created_at'], name='social_foll_followi_108864_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='feedview',
            index=models.Index(fields=['post', 'viewed_at'], name='social_feed_post_id_9e6cd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedview',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='social_favo_user_id_d169f9_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['content_type', 'object_id'], name='social_favo_content_573d9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', 'created_at'], name='social_emai_user_id_b052db_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'created_at'], name='social_emai_status_efeac8_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type', 'created_at'], name='social_emai_email_t_3c0916_idx'),
        ),
        migrations.AddIndex(
            model_name='contestvote',
            index=models.Index(fields=['contest', 'voter'], name='social_cont_contest_10504e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestvote',
            unique_together={('contest', 'entry', 'voter')},
        ),
        migrations.AlterUniqueTogether(
            name='contestentry',
            unique_together={('contest', 'participant')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='social_comm_content_d66c72_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='social_comm_author__c1cf89_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='social_comm_parent__758352_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['reply_to', 'created_at'], name='social_comm_reply_t_2c9ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatwallpaper',
            index=models.Index(fields=['user', 'chat'], name='social_chat_user_id_de2c72_idx'),
        ),
        migrations.AddIndex(
            model_name='chatwallpaper',
            index=models.Index(fields=['user', 'private_chat'], name='social_chat_user_id_119465_idx'),
        ),
        migrations.AddIndex(
            model_name='chatwallpaper',
            index=models.Index(fields=['is_preset'], name='social_chat_is_pres_5b84e0_idx'),
        ),
        migrations.AddIndex(
            model_name='chattypingstatus',
            index=models.Index(fields=['chat', 'typed_at'], name='social_chat_chat_id_c25080_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chattypingstatus',
            unique_together={('chat', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='chattopic',
            unique_together={('chat', 'anime')},
        ),
        migrations.AlterUniqueTogether(
            name='chattag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='chatsettings',
            unique_together={('user', 'chat')},
        ),
        migrations.AlterUniqueTogether(
            name='chatrole',
            unique_together={('chat', 'name')},
        ),
        migrations.AddIndex(
            model_name='chatrestriction',
            index=models.Index(fields=['chat', 'user'], name='social_chat_chat_id_f65e52_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrestriction',
            index=models.Index(fields=['until_date'], name='social_chat_until_d_23cdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['user', 'chat'], name='social_chat_user_id_325a71_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['is_admin'], name='social_chat_is_admi_3c2ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['is_banned'], name='social_chat_is_bann_a0cb94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together={('user', 'chat')},
        ),
        migrations.AddIndex(
            model_name='chatjoinrequest',
            index=models.Index(fields=['chat', 'status'], name='social_chat_chat_id_71a453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatjoinrequest',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatinvitelink',
            index=models.Index(fields=['invite_link'], name='social_chat_invite__434ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinvitelink',
            index=models.Index(fields=['chat', 'is_revoked'], name='social_chat_chat_id_b4818e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinvite',
            index=models.Index(fields=['token'], name='social_chat_token_df305e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatinvite',
            index=models.Index(fields=['chat', 'is_active'], name='social_chat_chat_id_1b4636_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatfolderchat',
            unique_together={('folder', 'chat_id')},
        ),
        migrations.AlterUniqueTogether(
            name='chatfolder',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='chatban',
            index=models.Index(fields=['chat', 'user'], name='social_chat_chat_id_883dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatban',
            index=models.Index(fields=['until_date'], name='social_chat_until_d_2fab5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatban',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatadminlog',
            index=models.Index(fields=['chat', 'created_at'], name='social_chat_chat_id_a25813_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='social_book_user_id_cf9227_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'folder'], name='social_book_user_id_c6711f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='social_atta_message_8d56ba_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['type'], name='social_atta_type_0f3204_idx'),
        ),
    ]
