# Generated by Django 4.2.10 on 2026-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_chatsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
