# Generated by Django 4.2.10 on 2026-01-22 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_message_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('invite_link', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('max_members', models.IntegerField(default=200)),
                ('slow_mode_delay', models.IntegerField(default=0)),
                ('history_visible', models.BooleanField(default=True)),
                ('can_send_media', models.BooleanField(default=True)),
                ('can_send_stickers', models.BooleanField(default=True)),
                ('can_send_polls', models.BooleanField(default=True)),
                ('can_add_web_page_previews', models.BooleanField(default=True)),
                ('can_change_info', models.BooleanField(default=True)),
                ('can_pin_messages', models.BooleanField(default=True)),
                ('can_invite_users', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(0, 'Участник'), (1, 'Модератор'), (2, 'Администратор'), (3, 'Владелец')], default=0)),
                ('color', models.CharField(default='#808080', max_length=7)),
                ('can_delete_messages', models.BooleanField(default=False)),
                ('can_ban_users', models.BooleanField(default=False)),
                ('can_pin_messages', models.BooleanField(default=False)),
                ('can_add_new_admins', models.BooleanField(default=False)),
                ('can_remain_anonymous', models.BooleanField(default=False)),
                ('can_manage_chat', models.BooleanField(default=False)),
                ('can_manage_video_chats', models.BooleanField(default=False)),
                ('can_restrict_members', models.BooleanField(default=False)),
                ('can_promote_members', models.BooleanField(default=False)),
                ('can_change_chat_info', models.BooleanField(default=False)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('can_post_messages', models.BooleanField(default=True)),
                ('can_edit_messages', models.BooleanField(default=False)),
                ('can_delete_chat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='social.groupchat')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('until_date', models.DateTimeField(blank=True, null=True)),
                ('custom_title', models.CharField(blank=True, max_length=32)),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('can_send_messages', models.BooleanField(default=True)),
                ('can_send_media', models.BooleanField(default=True)),
                ('can_add_reactions', models.BooleanField(default=True)),
                ('can_send_polls', models.BooleanField(default=True)),
                ('can_change_info', models.BooleanField(default=False)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('can_pin_messages', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.groupchat')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.chatrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('chat_created', 'Чат создан'), ('chat_updated', 'Настройки чата изменены'), ('member_joined', 'Участник присоединился'), ('member_left', 'Участник вышел'), ('member_banned', 'Участник забанен'), ('member_unbanned', 'Участник разбанен'), ('member_promoted', 'Участник повышен'), ('member_demoted', 'Участник понижен'), ('message_deleted', 'Сообщение удалено'), ('message_pinned', 'Сообщение закреплено'), ('message_unpinned', 'Сообщение откреплено'), ('invite_link_created', 'Пригласительная ссылка создана'), ('invite_link_revoked', 'Пригласительная ссылка отозвана'), ('slow_mode_changed', 'Режим медленной отправки изменен')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='social.groupchat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.message')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['created_at'], name='social_grou_created_ebb347_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['is_public'], name='social_grou_is_publ_127c76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatrole',
            unique_together={('chat', 'name')},
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['user', 'chat'], name='social_chat_user_id_325a71_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['is_admin'], name='social_chat_is_admi_3c2ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['is_banned'], name='social_chat_is_bann_a0cb94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together={('user', 'chat')},
        ),
        migrations.AddIndex(
            model_name='chatadminlog',
            index=models.Index(fields=['chat', 'created_at'], name='social_chat_chat_id_a25813_idx'),
        ),
    ]
