# Generated by Django 4.2.10 on 2026-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_groupchat_chatrole_chatmember_chatadminlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
