# Generated by Django 4.2.10 on 2026-01-22 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0008_chatmember_is_archived_chatmember_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user1_notifications', models.BooleanField(default=True)),
                ('user2_notifications', models.BooleanField(default=True)),
                ('user1_muted_until', models.DateTimeField(blank=True, null=True)),
                ('user2_muted_until', models.DateTimeField(blank=True, null=True)),
                ('user1_archived', models.BooleanField(default=False)),
                ('user2_archived', models.BooleanField(default=False)),
                ('user1_pinned', models.BooleanField(default=False)),
                ('user2_pinned', models.BooleanField(default=False)),
                ('user1_blocked', models.BooleanField(default=False)),
                ('user2_blocked', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='message_media/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chatsettings',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='social.groupchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='social.groupchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='social.message'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to='social.privatechat'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user1', 'last_message_at'], name='social_priv_user1_i_572f69_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user2', 'last_message_at'], name='social_priv_user2_i_d61c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user1', 'user1_pinned'], name='social_priv_user1_i_d69881_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechat',
            index=models.Index(fields=['user2', 'user2_pinned'], name='social_priv_user2_i_9fcb4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
