# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studiostaff',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='studiorating',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='studiorating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studionews',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studionews',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='studiodiscussionreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_discussion_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studiodiscussionreply',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='studios.studiodiscussion'),
        ),
        migrations.AddField(
            model_name='studiodiscussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studiodiscussion',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='studioaward',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='studioanime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_anime', to='studios.studio'),
        ),
        migrations.AlterUniqueTogether(
            name='studiosubscription',
            unique_together={('user', 'studio')},
        ),
        migrations.AlterUniqueTogether(
            name='studiorating',
            unique_together={('user', 'studio')},
        ),
        migrations.AlterUniqueTogether(
            name='studioanime',
            unique_together={('studio', 'kodik_id')},
        ),
    ]
