# Generated by Django 4.2.10 on 2026-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_phone_verified_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(default=list, verbose_name='Badges list'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Experience points'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mana',
            field=models.IntegerField(default=0, verbose_name='Mana currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='playlists_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
