# Generated by Django 4.2.10 on 2026-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_badges_user_comments_count_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone verified'),
        ),
    ]
