# Generated by Django 4.2.10 on 2026-01-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Display name'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.JSONField(default=list, verbose_name='Favorite genres'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Two factor enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Two factor secret'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_profile',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('auto', 'Автоматическая')], default='light', max_length=20, verbose_name='Theme')),
                ('ui_style', models.CharField(choices=[('modern', 'Современный'), ('classic', 'Классический'), ('minimal', 'Минималистичный'), ('dark', 'Тёмный')], default='modern', max_length=20, verbose_name='UI Style')),
                ('text_size', models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой')], default='medium', max_length=20, verbose_name='Text Size')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push notifications')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email notifications')),
                ('message_notifications', models.BooleanField(default=True, verbose_name='Message notifications')),
                ('contest_notifications', models.BooleanField(default=False, verbose_name='Contest notifications')),
                ('show_in_search', models.BooleanField(default=True, verbose_name='Show in search')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='Show online status')),
                ('show_stats', models.BooleanField(default=True, verbose_name='Show statistics')),
                ('personalized_recommendations', models.BooleanField(default=True, verbose_name='Personalized recommendations')),
                ('selected_interests', models.JSONField(default=list, verbose_name='Selected interests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User settings',
                'verbose_name_plural': 'User settings',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Device info')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User session',
                'verbose_name_plural': 'User sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
