# Generated by Django 4.2.10 on 2026-01-22 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_groupchat_chatrole_chatmember_chatadminlog_and_more'),
        ('users', '0008_user_display_name_user_favorite_genres_user_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_last_seen', models.BooleanField(default=True)),
                ('show_typing_status', models.BooleanField(default=True)),
                ('allow_calls', models.BooleanField(default=True)),
                ('allow_group_invites', models.BooleanField(default=True)),
                ('who_can_add_to_groups', models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Только контакты'), ('nobody', 'Никто')], default='everyone', max_length=20)),
                ('sync_contacts', models.BooleanField(default=True)),
                ('suggest_frequent_contacts', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('system', 'Как в системе'), ('blue', 'Синяя'), ('green', 'Зеленая')], default='system', max_length=20)),
                ('accent_color', models.CharField(default='#0084FF', max_length=7)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50)),
                ('date_format', models.CharField(choices=[('dd.mm.yyyy', 'ДД.ММ.ГГГГ'), ('mm/dd/yyyy', 'ММ/ДД/ГГГГ'), ('yyyy-mm-dd', 'ГГГГ-ММ-ДД')], default='dd.mm.yyyy', max_length=20)),
                ('time_format', models.CharField(choices=[('24', '24 часа'), ('12', '12 часов')], default='24', max_length=10)),
                ('notification_sound', models.CharField(default='default', max_length=100)),
                ('vibration', models.BooleanField(default=True)),
                ('preview_content', models.BooleanField(default=True)),
                ('login_notifications', models.BooleanField(default=True)),
                ('password_changed_notification', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки профиля',
                'verbose_name_plural': 'Настройки профилей',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('media_sent', models.IntegerField(default=0)),
                ('calls_made', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('favorite_chat_type', models.CharField(blank=True, max_length=20)),
                ('most_active_hour', models.IntegerField(blank=True, null=True)),
                ('average_response_time', models.IntegerField(default=0)),
                ('primary_device', models.CharField(blank=True, max_length=100)),
                ('last_used_device', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('collected_since', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Analytics',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=32)),
                ('backup_codes', models.JSONField(default=list)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('require_on_new_device', models.BooleanField(default=True)),
                ('remember_device_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_can_see_phone', models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Контакты'), ('nobody', 'Никто')], default='contacts', max_length=20)),
                ('who_can_see_email', models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Контакты'), ('nobody', 'Никто')], default='contacts', max_length=20)),
                ('who_can_see_last_seen', models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Контакты'), ('nobody', 'Никто')], default='everyone', max_length=20)),
                ('who_can_see_profile_photo', models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Контакты'), ('nobody', 'Никто')], default='everyone', max_length=20)),
                ('allow_message_forwarding', models.BooleanField(default=True)),
                ('who_can_call', models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Контакты'), ('nobody', 'Никто')], default='everyone', max_length=20)),
                ('who_can_add_to_groups', models.CharField(choices=[('everyone', 'Все'), ('contacts', 'Контакты'), ('nobody', 'Никто')], default='everyone', max_length=20)),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_notifications', models.BooleanField(default=True)),
                ('group_notifications', models.BooleanField(default=True)),
                ('call_notifications', models.BooleanField(default=True)),
                ('mention_notifications', models.BooleanField(default=True)),
                ('reaction_notifications', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_sound', models.BooleanField(default=True)),
                ('push_vibration', models.BooleanField(default=True)),
                ('push_preview', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('immediately', 'Немедленно'), ('hourly', 'Каждый час'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='immediately', max_length=20)),
                ('mute_until', models.DateTimeField(blank=True, null=True)),
                ('do_not_disturb_start', models.TimeField(blank=True, null=True)),
                ('do_not_disturb_end', models.TimeField(blank=True, null=True)),
                ('override_chat_settings', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chat_backgrounds/')),
                ('thumbnail', models.ImageField(upload_to='chat_backgrounds/thumbnails/')),
                ('is_default', models.BooleanField(default=False)),
                ('opacity', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_backgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#0084FF', max_length=7)),
                ('secondary_color', models.CharField(default='#00C853', max_length=7)),
                ('background_color', models.CharField(default='#373737', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_text_color', models.CharField(default='#666666', max_length=7)),
                ('message_bubble_radius', models.IntegerField(default=12)),
                ('show_message_time', models.BooleanField(default=True)),
                ('compact_mode', models.BooleanField(default=False)),
                ('chat_background', models.ImageField(blank=True, null=True, upload_to='chat_backgrounds/')),
                ('chat_background_opacity', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_via', models.CharField(choices=[('push', 'Push уведомление'), ('email', 'Email уведомление'), ('sms', 'SMS уведомление')], max_length=20)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'message', 'notified_via')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'sent_at'], name='users_email_user_id_0ca7a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_info', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'last_activity'], name='users_activ_user_id_fc7f1c_idx')],
            },
        ),
    ]
