# Generated by Django 4.2.10 on 2026-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Unique ID'),
        ),
    ]
