# Generated by Django 4.2.10 on 2026-06-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reactor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reactorpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactor_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reactorlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reactor.reactorpost'),
        ),
        migrations.AddField(
            model_name='reactorlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactor_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reactorcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reactor.reactorcomment'),
        ),
        migrations.AddField(
            model_name='reactorcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reactor.reactorpost'),
        ),
        migrations.AddField(
            model_name='reactorcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactor_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reactorpost',
            index=models.Index(fields=['user', 'created_at'], name='reactor_rea_user_id_c8dee1_idx'),
        ),
        migrations.AddIndex(
            model_name='reactorpost',
            index=models.Index(fields=['is_published', 'created_at'], name='reactor_rea_is_publ_49d623_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactorlike',
            unique_together={('user', 'post')},
        ),
    ]
